name: Weather data fetch

on:
  schedule:
    - cron: '0 9,13,20 * * *'
  workflow_dispatch:

jobs:
  sync-weather-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install firebase-admin requests

      - name: Print current directory path
        run: |
          echo "Current directory: $(pwd)"

      - name: List files in the directory
        run: |
          echo "Listing files:"
          ls -la

      - name: Create credentials file
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > ApiaryMonitoringSystem/config/firebase-credentials.json

      - name: Run weather data script
        run: |
          python ApiaryMonitoringSystem/scripts/weather.py
